name: WelcomeHead
version: '1.0'
main: org.padrewin.welcomehead.WelcomeHead
author: padrewin
api-version: '1.20'
description: A plugin that shows player's head with a welcome message on server join.
depend: [PlaceholderAPI]
commands:
  welcomehead:
    description: The main command.
    aliases: [wh]
    permission: welcomehead.use